import type { Congestion, Onsen, Review } from '../types/onsen';

const noWinterClosure = { start: '12-01', end: '03-31', enabled: false };

export const onsens: Onsen[] = [
  {
    id: 'tsukioka_hoshinoya_001',
    name: '月岡温泉 星野屋 日帰り湯',
    areaName: '月岡温泉',
    prefecture: '新潟県',
    city: '新発田市',
    area: '月岡',
    address: '新潟県新発田市月岡温泉123',
    region: '下越',
    latitude: 37.8456,
    longitude: 139.3812,
    hours: '10:00〜21:00',
    regularHours: '',
    lodgerBathHours: '',
    privateBathHours: '',
    features: { rotenburo: true, sauna: true, restaurant: true, parking: true },
    description: '硫黄成分を豊富に含む緑色の湯が特徴。美肌効果で知られる新潟屈指の名湯。',
    components: '含硫黄-ナトリウム-塩化物泉',
    effects: '美肌、神経痛、筋肉痛、冷え性',
    price: { adult: 800, child: 400, childCondition: '小学生（6〜12歳）。未就学児は無料', paymentMethod: '現金のみ' },
    capacity: { total: 25, male: 12, female: 12 },
    phone: '0254-32-1234',
    website: 'https://example-tsukioka.jp',
    accessInfo: '',
    hasLodging: false,
    lodgingUrl: '',
    regularHoliday: '毎週火曜日',
    winterClosure: noWinterClosure,
    isTemporarilyClosed: false,
    photos: [
      'https://picsum.photos/seed/tsukioka1/900/650',
      'https://picsum.photos/seed/tsukioka1b/900/650',
    ],
  },
  {
    id: 'tsukioka_midorinoyu_002',
    name: '月岡温泉 みどりの湯',
    areaName: '月岡温泉',
    prefecture: '新潟県',
    city: '新発田市',
    area: '月岡',
    address: '新潟県新発田市月岡温泉89',
    region: '下越',
    latitude: 37.8462,
    longitude: 139.3799,
    hours: '11:00〜20:00',
    regularHours: '',
    lodgerBathHours: '',
    privateBathHours: '',
    features: { rotenburo: true, sauna: false, restaurant: false, parking: true },
    description: '地元の人にも愛される小規模な共同浴場スタイルの日帰り湯。',
    components: '含硫黄-ナトリウム-塩化物泉',
    effects: '美肌、疲労回復',
    price: { adult: 600, child: 300, childCondition: '小学生以下', paymentMethod: '現金のみ' },
    capacity: { total: 14, male: 7, female: 7 },
    phone: '0254-32-5678',
    website: 'https://example-midorinoyu.jp',
    accessInfo: '',
    hasLodging: false,
    lodgingUrl: '',
    regularHoliday: '毎週水曜日',
    winterClosure: noWinterClosure,
    isTemporarilyClosed: false,
    photos: ['https://picsum.photos/seed/midorinoyu/900/650'],
  },
  {
    id: 'senami_shiomi_003',
    name: '瀬波温泉 汐美の湯',
    areaName: '瀬波温泉',
    prefecture: '新潟県',
    city: '村上市',
    area: '瀬波',
    address: '新潟県村上市瀬波温泉2丁目1',
    region: '下越',
    latitude: 38.2223,
    longitude: 139.475,
    hours: '10:00〜22:00',
    regularHours: '',
    lodgerBathHours: '',
    privateBathHours: '',
    features: { rotenburo: true, sauna: true, restaurant: true, parking: true },
    description: '日本海に面し、水平線に沈む夕陽を望む露天風呂が名物。',
    components: 'ナトリウム-塩化物強塩温泉',
    effects: '神経痛、関節痛、冷え性、疲労回復',
    price: { adult: 900, child: 450, childCondition: '小学生（6〜12歳）', paymentMethod: '現金のみ' },
    capacity: { total: 30, male: 16, female: 14 },
    phone: '0254-53-2233',
    website: 'https://example-senami.jp',
    accessInfo: '',
    hasLodging: false,
    lodgingUrl: '',
    regularHoliday: '不定休',
    winterClosure: noWinterClosure,
    isTemporarilyClosed: false,
    photos: ['https://picsum.photos/seed/senami/900/650'],
  },
  {
    id: 'iwamuro_yumoto_004',
    name: '岩室温泉 湯元 弥彦の湯',
    areaName: '岩室温泉',
    prefecture: '新潟県',
    city: '新潟市西蒲区',
    area: '岩室',
    address: '新潟県新潟市西蒲区岩室温泉611',
    region: '下越',
    latitude: 37.7809,
    longitude: 138.9727,
    hours: '10:00〜21:00',
    regularHours: '',
    lodgerBathHours: '',
    privateBathHours: '',
    features: { rotenburo: true, sauna: true, restaurant: true, parking: true },
    description: '弥彦山を望む静かな湯治場。国道からすぐの立地で日帰り利用も多い。',
    components: 'カルシウム-ナトリウム-硫酸塩泉',
    effects: '筋肉痛、関節痛、五十肩、慢性消化器病',
    price: { adult: 700, child: 350, childCondition: '小学生以下', paymentMethod: '現金のみ' },
    capacity: { total: 20, male: 10, female: 10 },
    phone: '0256-82-1122',
    website: 'https://example-iwamuro.jp',
    accessInfo: '',
    hasLodging: false,
    lodgingUrl: '',
    regularHoliday: '毎週木曜日',
    winterClosure: noWinterClosure,
    isTemporarilyClosed: false,
    photos: ['https://picsum.photos/seed/iwamuro/900/650'],
  },
  {
    id: 'sakihana_kawazoi_005',
    name: '咲花温泉 川沿いの宿 日帰り湯',
    areaName: '咲花温泉',
    prefecture: '新潟県',
    city: '五泉市',
    area: '咲花',
    address: '新潟県五泉市佐取咲花温泉38',
    region: '下越',
    latitude: 37.728,
    longitude: 139.354,
    hours: '11:00〜19:00',
    regularHours: '',
    lodgerBathHours: '',
    privateBathHours: '',
    features: { rotenburo: true, sauna: false, restaurant: true, parking: true },
    description: '阿賀野川のせせらぎを聞きながら入れる、ラジウムを含む珍しい泉質。',
    components: '含放射能-ナトリウム-塩化物泉',
    effects: '高血圧症、動脈硬化症、痛風',
    price: { adult: 650, child: 300, childCondition: '小学生以下', paymentMethod: '現金のみ' },
    capacity: { total: 16, male: 8, female: 8 },
    phone: '0250-47-3344',
    website: 'https://example-sakihana.jp',
    accessInfo: '',
    hasLodging: false,
    lodgingUrl: '',
    regularHoliday: '毎週月曜日',
    winterClosure: noWinterClosure,
    isTemporarilyClosed: false,
    photos: ['https://picsum.photos/seed/sakihana/900/650'],
  },
  {
    id: 'tochiomata_hyakusai_006',
    name: '栃尾又温泉 百歳の湯',
    areaName: '栃尾又温泉',
    prefecture: '新潟県',
    city: '魚沼市',
    area: '栃尾又',
    address: '新潟県魚沼市上折立栃尾又温泉',
    region: '中越',
    latitude: 37.133,
    longitude: 139.023,
    hours: '9:00〜20:00',
    regularHours: '',
    lodgerBathHours: '',
    privateBathHours: '',
    features: { rotenburo: false, sauna: false, restaurant: true, parking: true },
    description: '「子宝の湯」として知られる山あいの秘湯。ぬる湯にじっくり浸かるのが流儀。',
    components: '単純放射能温泉（ラジウム泉）',
    effects: '婦人科系疾患、リウマチ、皮膚病',
    price: { adult: 600, child: 300, childCondition: '小学生以下', paymentMethod: '現金のみ' },
    capacity: { total: 12, male: 6, female: 6 },
    phone: '025-795-2211',
    website: 'https://example-tochiomata.jp',
    accessInfo: '',
    hasLodging: false,
    lodgingUrl: '',
    regularHoliday: '不定休',
    winterClosure: { start: '01-10', end: '03-20', enabled: true },
    isTemporarilyClosed: false,
    photos: ['https://picsum.photos/seed/tochiomata/900/650'],
  },
  {
    id: 'yuzawa_takahan_007',
    name: '越後湯沢温泉 高半 日帰り湯',
    areaName: '越後湯沢温泉',
    prefecture: '新潟県',
    city: '南魚沼郡湯沢町',
    area: '湯沢',
    address: '新潟県南魚沼郡湯沢町大字湯沢923',
    region: '上越',
    latitude: 36.9337,
    longitude: 138.8058,
    hours: '10:00〜21:00',
    regularHours: '',
    lodgerBathHours: '',
    privateBathHours: '',
    features: { rotenburo: true, sauna: true, restaurant: true, parking: true },
    description: '川端康成「雪国」ゆかりの老舗宿。開湯800年を誇る温泉街の中心的存在。',
    components: 'アルカリ性単純温泉',
    effects: '疲労回復、神経痛、冷え性',
    price: { adult: 1000, child: 500, childCondition: '小学生（6〜12歳）', paymentMethod: '現金のみ' },
    capacity: { total: 28, male: 14, female: 14 },
    phone: '025-784-3322',
    website: 'https://example-yuzawa-takahan.jp',
    accessInfo: '',
    hasLodging: true,
    lodgingUrl: 'https://example-yuzawa-takahan.jp/stay',
    regularHoliday: 'なし（年中無休）',
    winterClosure: noWinterClosure,
    isTemporarilyClosed: false,
    photos: [
      'https://picsum.photos/seed/yuzawa1/900/650',
      'https://picsum.photos/seed/yuzawa1b/900/650',
    ],
  },
  {
    id: 'yuzawa_komakan_008',
    name: '越後湯沢温泉 駒の湯',
    areaName: '越後湯沢温泉',
    prefecture: '新潟県',
    city: '南魚沼郡湯沢町',
    area: '湯沢',
    address: '新潟県南魚沼郡湯沢町大字湯沢410',
    region: '上越',
    latitude: 36.9351,
    longitude: 138.8091,
    hours: '10:00〜20:00',
    regularHours: '',
    lodgerBathHours: '',
    privateBathHours: '',
    features: { rotenburo: false, sauna: true, restaurant: false, parking: true },
    description: 'スキー客にも人気の、こぢんまりとした市街地の共同浴場。',
    components: 'アルカリ性単純温泉',
    effects: '疲労回復、筋肉痛',
    price: { adult: 550, child: 250, childCondition: '小学生以下', paymentMethod: '現金のみ' },
    capacity: { total: 15, male: 8, female: 7 },
    phone: '025-784-5566',
    website: 'https://example-komakan.jp',
    accessInfo: '',
    hasLodging: false,
    lodgingUrl: '',
    regularHoliday: '毎週水曜日',
    winterClosure: noWinterClosure,
    isTemporarilyClosed: false,
    photos: ['https://picsum.photos/seed/komakan/900/650'],
  },
  {
    id: 'akakura_kanko_009',
    name: '赤倉温泉 観光ホテル 日帰り湯',
    areaName: '赤倉温泉',
    prefecture: '新潟県',
    city: '妙高市',
    area: '赤倉',
    address: '新潟県妙高市赤倉温泉67',
    region: '上越',
    latitude: 36.8969,
    longitude: 138.2214,
    hours: '10:00〜21:00',
    regularHours: '',
    lodgerBathHours: '',
    privateBathHours: '',
    features: { rotenburo: true, sauna: true, restaurant: true, parking: true },
    description: '妙高山の麓に湧く、スキーリゾートとしても名高い高原温泉。',
    components: '硫黄泉',
    effects: '慢性皮膚病、糖尿病、動脈硬化症',
    price: { adult: 850, child: 400, childCondition: '小学生（6〜12歳）', paymentMethod: '現金のみ' },
    capacity: { total: 22, male: 11, female: 11 },
    phone: '0255-87-2211',
    website: 'https://example-akakura.jp',
    accessInfo: '',
    hasLodging: true,
    lodgingUrl: 'https://example-akakura.jp/stay',
    regularHoliday: 'なし（年中無休）',
    winterClosure: noWinterClosure,
    isTemporarilyClosed: false,
    photos: ['https://picsum.photos/seed/akakura/900/650'],
  },
  {
    id: 'matsunoyama_kyokan_010',
    name: '松之山温泉 凌雲閣 日帰り湯',
    areaName: '松之山温泉',
    prefecture: '新潟県',
    city: '十日町市',
    area: '松之山',
    address: '新潟県十日町市松之山湯本14',
    region: '上越',
    latitude: 37.009,
    longitude: 138.679,
    hours: '11:00〜20:00',
    regularHours: '',
    lodgerBathHours: '',
    privateBathHours: '',
    features: { rotenburo: true, sauna: false, restaurant: true, parking: true },
    description: '日本三大薬湯のひとつ。塩分濃度の高い茶褐色の湯が特徴。',
    components: 'ナトリウム-カルシウム-塩化物強塩温泉',
    effects: '婦人科系疾患、腰痛、冷え性',
    price: { adult: 800, child: 400, childCondition: '小学生（6〜12歳）', paymentMethod: '現金のみ' },
    capacity: { total: 18, male: 9, female: 9 },
    phone: '025-596-2011',
    website: 'https://example-matsunoyama.jp',
    accessInfo: '',
    hasLodging: true,
    lodgingUrl: 'https://example-matsunoyama.jp/stay',
    regularHoliday: '毎週金曜日',
    winterClosure: noWinterClosure,
    isTemporarilyClosed: true,
    photos: ['https://picsum.photos/seed/matsunoyama/900/650'],
  },
];

function makeCongestion(onsenId: string, usersMale: number, usersFemale: number, unknown: number, groups: number): Congestion {
  const onsen = onsens.find((o) => o.id === onsenId)!;
  const usersCount = usersMale + usersFemale + unknown;
  return {
    onsenId,
    timestamp: new Date().toISOString(),
    usersCount,
    groupsCount: groups,
    congestionRate: Math.round((usersCount / onsen.capacity.total) * 100),
    male: { usersCount: usersMale, congestionRate: Math.round((usersMale / onsen.capacity.male) * 100) },
    female: { usersCount: usersFemale, congestionRate: Math.round((usersFemale / onsen.capacity.female) * 100) },
    unknownCount: unknown,
  };
}

export const congestions: Congestion[] = [
  makeCongestion('tsukioka_hoshinoya_001', 3, 4, 1, 5),
  makeCongestion('tsukioka_midorinoyu_002', 5, 5, 0, 5),
  makeCongestion('senami_shiomi_003', 12, 9, 2, 11),
  makeCongestion('iwamuro_yumoto_004', 2, 3, 0, 3),
  makeCongestion('sakihana_kawazoi_005', 1, 2, 0, 2),
  makeCongestion('tochiomata_hyakusai_006', 2, 2, 0, 2),
  makeCongestion('yuzawa_takahan_007', 11, 12, 1, 12),
  makeCongestion('yuzawa_komakan_008', 6, 5, 0, 6),
  makeCongestion('akakura_kanko_009', 4, 3, 1, 4),
  makeCongestion('matsunoyama_kyokan_010', 0, 0, 0, 0),
];

export function getCongestion(onsenId: string): Congestion {
  return congestions.find((c) => c.onsenId === onsenId) ?? makeCongestion(onsenId, 0, 0, 0, 0);
}

export const reviews: Review[] = [
  {
    id: 'rv_001',
    onsenId: 'tsukioka_hoshinoya_001',
    userId: 'mock-other-user-1',
    userName: 'ゆのすけ',
    userAvatar: 'https://picsum.photos/seed/avatar1/100/100',
    rating: 5,
    comment: '緑色の湯が本当にきれいでした。露天からの眺めも最高です。',
    createdAt: '2026-06-20T18:30:00+09:00',
    status: 'visible',
  },
  {
    id: 'rv_002',
    onsenId: 'tsukioka_hoshinoya_001',
    userId: 'mock-other-user-2',
    userName: 'にいがた温泉部',
    userAvatar: 'https://picsum.photos/seed/avatar2/100/100',
    rating: 4,
    comment: '土曜の午後は少し混みますが、平日はゆったり入れました。',
    createdAt: '2026-06-15T12:10:00+09:00',
    status: 'visible',
  },
  {
    id: 'rv_003',
    onsenId: 'yuzawa_takahan_007',
    userId: 'mock-other-user-3',
    userName: 'スキーヤーA',
    userAvatar: 'https://picsum.photos/seed/avatar3/100/100',
    rating: 5,
    comment: 'スキー帰りに最高。体の芯から温まりました。',
    createdAt: '2026-07-01T20:00:00+09:00',
    status: 'visible',
  },
];

// 直近訪問履歴（マイページ用のモック）
export const recentVisits = [
  { onsenId: 'tsukioka_hoshinoya_001', visitedAt: '2026-07-05T14:20:00+09:00' },
  { onsenId: 'senami_shiomi_003', visitedAt: '2026-06-28T10:05:00+09:00' },
  { onsenId: 'yuzawa_takahan_007', visitedAt: '2026-06-14T16:40:00+09:00' },
];

export const favoriteOnsenIds = ['tsukioka_hoshinoya_001', 'yuzawa_takahan_007'];

export const popularRanking = [
  'tsukioka_hoshinoya_001',
  'yuzawa_takahan_007',
  'senami_shiomi_003',
  'akakura_kanko_009',
  'yuzawa_komakan_008',
];

export const recommended = ['matsunoyama_kyokan_010', 'sakihana_kawazoi_005', 'tochiomata_hyakusai_006'];
